### ISSUE TITLE
Use of empty passwords 

### ISSUE THREAD

**Issue by akondasif** [duritong/puppet-tor#14]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts. I noticed instances of empty passwords. Empty passwords increase the guessability of passwords. The Common Weakness Organization (CWE) identifies use of empty passwords as a security weakness (https://cwe.mitre.org/data/definitions/258.html). 

I suggest that to follow the strong password guidelines, and manage passwords with hiera.  

Any feedback is appreciated.  

Source: https://github.com/duritong/puppet-tor/blob/master/manifests/daemon/control.pp

**Comment by duritong** [comment]
If you look at the code https://github.com/duritong/puppet-tor/blob/master/manifests/daemon/control.pp#L12 and https://github.com/duritong/puppet-tor/blob/master/templates/torrc.control.erb, you would see that you can't have an empty password if it will actually end up in the config file.

So I don't see the issue here and how hiera could have done any difference.

Thanks

**Comment by akondasif** [comment]
Thanks for the feedback.
